### ISSUE TITLE
Unable to enter devshell due to missing PRJ_ROOT in environment

### ISSUE THREAD

**Issue by cscutcher** [divnix/std#101]
As a way to experiment with `std` I wanted to try a very simple devshell example. However it seems like, due to a missing `PRJ_ROOT` environment variable, I'm unable to enter that environment.

I've created [cscutcher/simple_devshell_std](https://github.com/cscutcher/simple_devshell_std) as a minimal example of the issue. When running on my ArchLinux based environment I get; 

```console
❯ nix run github:divnix/std -- '//simple/devshell/default:enter'
mkdir: cannot create directory ‘/.std’: Permission denied
error: '#x86_64-linux.simple.devshell.default' is not a valid URL
bash: line 1: /.std/simple/devshell/default/shell-profile/env.bash: No such file or directory
bash: line 1: __devshell-motd: command not found
```

but if I explicitly set `PRJ_ROOT` to `$PWD` it works as expected;

```console
❯ nix run github:divnix/std -- '//simple/devshell/default:enter'
mkdir: cannot create directory ‘/.std’: Permission denied
error: '#x86_64-linux.simple.devshell.default' is not a valid URL
bash: line 1: /.std/simple/devshell/default/shell-profile/env.bash: No such file or directory
bash: line 1: __devshell-motd: command not found
```

Best I can tell reading the source and docs of the involved projects is that it seems unavoidable since `.std/last-action` contains;

```bash
#!/nix/store/qm2lv1gpbyn0rsfai40cbvj3h4gz69yc-bash-5.1-p16/bin/bash
std_layout_dir=$PRJ_ROOT/.std
profile_path="$std_layout_dir/simple/devshell/default"
mkdir -p "$profile_path"
nix_args=(
  "$PRJ_ROOT#"x86_64-linux"."simple"."devshell"."default""
  "--no-update-lock-file"
  "--no-write-lock-file"
  "--no-warn-dirty"
  "--accept-flake-config"
  "--no-link"
  "--keep-outputs"
  "--build-poll-interval" "0"
)
nix build "${nix_args[@]}" --profile "$profile_path/shell-profile"
bash -c "source $profile_path/shell-profile/env.bash; SHLVL=$SHLVL; __devshell-motd; exec $SHELL -i"
```

and I'm running with the assumption that setting `$PRJ_ROOT` manually isn't *intended* to be a requirement.  

I'm very new to `std`, love the idea, but struggled a bit with the documentation so apologies if I'm misusing it. Also unfamiliar with the projects this functionality appears to be built on top of, including `devshell` and `nixago`, so plenty of room for me to get the wrong end of the stick! Up to now I've only used `flake-utils` and "vanilla" nix `mkShell`, hell I'm relatively new to the whole nix ecosystem so apologies in advance for my ignorance!

**Comment by GTrunSec** [comment]
you can not run this command with `nix run`. please try the `nix develop --command` instead.

**Comment by cscutcher** [comment]
Oh man! That easy eh! As you say;

```console
❯ nix develop 'github:divnix/std' -c std '//simple/devshell/default:enter'
```

worked well enough that I could get the rest of the way. Thanks! 😃 Did I miss that documented somewhere? 

I also finally realised that adding;

```diff
diff --git a/flake.nix b/flake.nix
index 84e1232..befc806 100644
--- a/flake.nix
+++ b/flake.nix
@@ -3,12 +3,17 @@
   inputs.nixpkgs.url = "nixpkgs";

   outputs = { std, ... } @ inputs:
-    std.grow
+    std.growOn
       {
         inherit inputs;
         cellsFrom = ./cells;
         organelles = [
           (std.devshells "devshell")
         ];
+      }
+      # soil for compatiblity ...
+      {
+        # ... with `nix develop` - `default` is a special target for `nix develop`
+        devShells = inputs.std.harvest inputs.self [ "simple" "devshell" ];
       };
 }
```

Would allow me to just run `nix develop` without needing to directly invoke `std`. I'd seen that snippet around in docs and examples but it took me ages to grok what it was doing, despite the comment!

---

**Am I right in thinking there's still a bug here though?**

For the "Hello World" tutorial in the docs it uses `nix shell github:divnix/std` to get the `std` command to allow running `std //hello/apps/default:run` but that would make the situation with `devshells` inconsistent right? 
Equally, it feels a little strange that `nix develop 'github:divnix/std'` would assume that the current director is a clone of the `std` repo, and then start writing out config files and profiles there?

As a suggestion, at minimal it might be a good idea to ensure the `devshells` command fails early with a solid error message if `PRJ_ROOT` isn't set. That would at least help people work out what's going on if they make a naive mistake like me, and it would prevent accidentally writing to root at `/.std`. I'd hope that people aren't running with root privileges but better safe than sorry! wdyt?

Obviously would be nicer if there was some way to make it work even without `PRJ_ROOT` being set explicitly so that `nix run github:divnix/std` (or `nix shell`) would allow entering devshell via TUI/CLI, but I don't think I know enough to make useful suggestions! Writing the `.std` dir to a temporary location if `PRJ_ROOT` is unset seems sensible, or [the spec](https://github.com/numtide/prj-spec/blob/main/PRJ_SPEC.md) (that I assume `$PRJ_ROOT` is derived from) looks like it has a concept of `PRJ_ID` and `PRJ_CACHE_HOME` with the latter defaulting to `${XDG_CACHE_HOME}/prj/${PRJ_ID}` if the former is set. I was going to suggest the global `inputs.self` for discovery the flake location for the `nix_args=(` part of the command, but then I noticed the `std` docs warn against abusing that!

Sorry if the suggestions aren't much help! But I figured I'd have a stab in the dark.

**Comment by blaggacao** [comment]
> I'm running with the assumption that setting $PRJ_ROOT manually isn't intended to be a requirement.

`$PRJ_ROOT` is a contract that is usually satisfied by `direnv` when used together with `numtide/devshell`. Given the tight coupling of these two tools with `std`, we consume that contract, as well. See for example: https://github.com/numtide/devshell/blob/fc463a543e2bc497a6d0bae17fc88aa7e0cec5ee/modules/devshell.nix#L61-L67

Or indirectly via (by wrapping `numtide/devshell`): https://github.com/divnix/std/blob/main/direnv_lib.sh

Conclusion: as of now, only a `numtide/devshell` environment does guarantee `PRJ_ROOT` contract.

---

You are right that the Hello World example is inconsistent with that premise. It doesn't enter a devshell.

> `nix develop 'github:divnix/std'`

This wouldn't have a sensible meaning: "Hack on 'divnix/std' - but on a non-writable copy". &mdash; the nix ecosystem is still stuck a little bit with proper semantics for `nix develop` (e.g. in comparison to what `numtide/devshell` insinuates through hijacking that mechanism very elegantly).

---

I think one way to satisfy the contract would be for `std` to fall back on detecting the git repo root (or fail). That would also heal the Hello World example.

Thank you for highlighting this error, which doesn't occur on my daily routines (due tho the `numtide/devshell` contracts) and hence I've been overlooking this.

**Comment by blaggacao** [comment]
@cscutcher can you check again with https://github.com/divnix/std/pull/103 merged?

**Comment by cscutcher** [comment]
@blaggacao looks much better!

```console
❯ nix run github:divnix/std -- '//simple/devshell/default:enter'

🔨 Welcome to Simple Test Devshell 🔨

To autocomplete 'std' in bash, zsh, oil: source <(std _carapace)
More shells: https://rsteube.github.io/carapace/carapace/gen/hiddenSubcommand.html


[general commands]

  menu - prints this menu
  std  - A tui for projects that conform to Standard

❯ hello
Hello, world!

```

also checked with `nix shell` env too;

```console
❯ nix shell github:divnix/std
❯ std '//simple/devshell/default:enter'

🔨 Welcome to Simple Test Devshell 🔨

To autocomplete 'std' in bash, zsh, oil: source <(std _carapace)
More shells: https://rsteube.github.io/carapace/carapace/gen/hiddenSubcommand.html


[general commands]

  menu - prints this menu
  std  - A tui for projects that conform to Standard

❯ hello
Hello, world!
```

Thanks for taking the time to look at the issue!
