### ISSUE TITLE
Cell -> Cell | Organelle -> Cell Block | Clade -> Block Type

### ISSUE THREAD

**Issue by blaggacao** [divnix/std#116]
Let's revert the idea that "cell" conditions it's helpless looking subconcepts.

**Comment by uningan** [comment]
You have here some info to develop new flake related metaphor:
https://en.wikipedia.org/wiki/Snowflake

Cell -> Ice Nucleus
Organelle -> Water droplet
Clade -> Droplet shape

**Comment by blaggacao** [comment]
@uningan Thank you very much for the suggestion!

One of the most prevalent critiques of Standard has been the creative use of names.

The original goal has been to choose names _sufficiently_ distinct that they safe the purpose of breaking with any nix-anchored path-dependent semantics.

Let loose the chains of the current schemata and conventions and enable outside-the-box thinking.

It should also have been distinct enough to be able to reference the name tokens largely context free to a knowledgeable interlocutor. I.e. just say "organelle" instead of "the thing that is on the second layer of the folder structure, you know what I mean".

We can't pretend we wouldn't have a naming crisis in Nix, anyway. 😁

--;

But then, people found the biological analogy too far fetched. Partly because "organelle" and "clade" might have been concepts that needed a refresher dictionary lookup.

These names, instead of transporting the abstract semantic relationship, became a mental alias to another denomination (almost always something that includes words from type theory) that would more closely resemble the actual mental model.

That extra effort is definitely an intuition blocked, whereas Standard regards intuition as a emancipated toolset alongside documentation et al.

---

With the choosing of:

- Cell
- Cell Block
- Block Type

We are building a clear logical chain that could even infer a residual semantic relationship in case you wouldn't understand the words at all:

- Fer
- Fer Gar
- Gar Ti

It is clear that the first is related to the second, while the second is related to the last, and so: Fer Gar Ti cand mean something. So cab Cell Block Type.

Hence the new choice.

QED.

**Comment by nrdxp** [comment]
This breaks flakes that still have an old reference to `std` somewhere in the lockfile, since the type checking fails on any blocks they import.
