### ISSUE TITLE
proposal: rename `inputs` to `flake`

### ISSUE THREAD

**Issue by nrdxp** [divnix/std#149]
It seems to me that `inputs` is a bit of a misnomer, especially since the the set also contains references to local cells via the `cells` attribute. I feel a far more appropriate name would simply be `flake`, analougous to the `crate` nomeclature in rust, (i.e `use crate::mod::myMod` == `inherit (flake.cells) myCell`).

Other possibilities include keeping inputs, but moving cells to the top: `{inputs, cells}` where `cells` contains the current `cell` reference, or it could just contain a named reference to itself to avoid any "special" attributes like `cell`.

We could also keep inputs but move them inside flake, so `{flake = { inputs, cells }, cell}`

It might even be nice to nest everything under flake: `{flake = { inputs, cells, cell }}`

Or combining the idea to have just `inputs` and `cells`, it could be `{flake = {inputs, cells = { this, other, ...}}}`

**Comment by jmgilman** [comment]
I feel the primary problem here is `cells` being hidden in `inputs`. I think `inputs` itself is fine enough of a name, and most people familiar with flakes should be able to piece together what it is just by looking at it. I'm probably more in favor of `cell` to `cells` or just adding `cells` as a third argument.

**Comment by blaggacao** [comment]
I think we don't want that level of renaming at this point. Granted it has a wired interpretation of `inputs.self` as an input that doesn't conform to the "flakes way", and it does special things with `nixpkgs` if present. But that's also about it.

`cells` are a middle ground that _should_ be considered inputs in the context of a particular cell, but aren't foreign inputs altogether.

**Comment by blaggacao** [comment]
While the naming may be hijacking an existing interpretation of `inputs` in the nix (sic!) ecosystem, language & concepts are hopefully flexible enough to accomodate this slightly modified semantics used in `std`.

In my opinion, the switching cost is in no relation to the benefits.
