### ISSUE TITLE
Allow a top-level README.md in `cellsFrom`

### ISSUE THREAD

**Issue by zeme-iohk** [divnix/std#159]
Putting anything that is not a folder (e.g. a README.md file) inside the `cellsFrom` folder throws an error:
```
Everything under ${cellsFrom}/* is considered a Cell
[...]
Please remove '${cellsFrom}/README.md' and don't forget to add the change to version control.
```
However I think that it would be useful to allow a README.md file in there, just like a README.md is allowed inside each cell's folder.
For my use case I was going to collect nix/std related documentation inside that file, targeting current and future nix maintainers.
I was going to include a high-level overview of the cells and the nix code in general, so it felt right to place it in `cellsFrom`.

In case this proposal isn't accepted, suggestions for alternative locations are welcome!

**Comment by blaggacao** [comment]
I'd reflexively think that I'd still rather have a specific whitelist, e.g. allow a Readme. Just to avoid that this folder starts containing glue code that it shouldn't or other content that rather should be categorized.

**Comment by zeme-iohk** [comment]
Yes, I was thinking to just allow a single file named README.md, that's it.

This is the "workaround" I used:
```
nix
- README.md
- cells 
- - cell1 
- - cell2
```
And in flake.nix, `cellsFrom = ./nix/cells`

In truth it's ok, I can definitely live with that, but would be better if I could have:

```
nix
- README.md
- cell1 
- cell2
```
And in flake.nix `cellsFrom = ./nix"

**Comment by blaggacao** [comment]
Would you want to attempt an implementation of special casing such a readme?  `./src/grow.nix` & `./src/validators.nix` and maybe `./nix/paths.nix` (to keep all path contracts in one file) are the relevant pieces.

**Comment by blaggacao** [comment]
After https://github.com/divnix/std/commit/672d323f93c48ceac191bbbbf5745d9c6e66678f you also can do something like:

```nix
{
      cellsFrom = std.incl ./src [ ./src/_automation ];
      # or
      cellsFrom = std.incl ./src [ "_automation" ];
      # or
      cellsFrom = std.incl (self.sourceInfo + /src) [ (self.sourceInfo + /src/_automation) ];
      # or
      cellsFrom = std.incl (self.sourceInfo + /src) [ "_automation" ];
}
```
