### ISSUE TITLE
newbie experience: a personal account

### ISSUE THREAD

**Issue by waalge** [divnix/std#163]
> ship today 

I want this. 

I've been trying to use nix for months now, and I still don't understand it. The divnix docs site is reaffirming in the sense that maybe its not just me but honestly nothing has made me feel more stupid than not being able to use nix.

Maybe these issues are unique to me. Perhaps they are others hitting the same problems and for that reason I'll put them here.

## running commentary

- The walk in the park links error for me (https://std.divnix.com/tutorials/walk-in-the-park.html) (too many redirection). 
Maybe its me, but I've tried multiple browsers, and curl but nothing. way back machine hasn't seen it, but some other, i guess older posts were available. 
- On hello world (https://std.divnix.com/tutorials/hello-world/index.html) I thought I was being invited to make a project with these two files as specified. It was not initially clear that if you are reading this from the repo, then these files are already there. Even then, the instructions say 
```
$ cd hello-world
```
which from the book made no sense, and from the repo is confusing, cos the doc is already inside a directory `hello-world`. 
```
# fetch `std`
$ nix shell github:divnix/std
```
Outputs: 
```
error: cannot write modified lock file of flake 'github:divnix/std' (use '--no-write-lock-file' to ignore)
(use '--show-trace' to show detailed location information)
```
Should I follow the prompt? the docs don't warn me about. GH issues has a hit on the error message (https://github.com/divnix/std/issues/101) but its a bit over my head. It looks like more nix magic. I'm not using direnv - I understood its highly recommended but not necessary. I tried to clone the repo, and run the commands in the concluding message . This works with the suggested flag. 
Back here, with the flag
```
$nix shell github:divnix/std --no-write-lock-file
warning: not writing modified lock file of flake 'github:divnix/std':
• Updated input 'n2c/flake-utils':
    'github:numtide/flake-utils/1ed9fb1935d260de5fe1c2f7ee0ebaae17ed2fa1' (2022-05-30)
  → follows 'flake-utils'
```
```
$std //hello/apps/default:run
warning: not writing modified lock file of flake 'git+file:///home/waalge/clones/std?dir=docs%2ftutorials%2fhello-world':
• Added input 'nixpkgs':
  # .... LINES OMMITED 
• Added input 'std/yants/nixpkgs':
    follows 'std/nixpkgs'
bash: line 1: /home/waalge/clones/std/.std/last-action: No such file or directory
```
Not quite the desired output. I stopped here with this

 
 - The rust template (https://std.divnix.com/templates/rust.html). This was a small problem. It assumes you have cargo on path, which is probably fair? I dunno. I don't. You definitely will after dropping into a dev shell so its a just an extra thing for noob to slip up on - as I did. Having run `cargo init` from inside the shell, `std` was confused. 
```
[devshell]$ std
2022/10/14 16:05:38 exit status 1
[devshell]$ std //hello/packages/:build
Error: invalid argument format: //hello/packages/:build
```
This last command is constructed by just hitting tab. 
It turns out that it needs a cargo lock file (and possibly it tracked? )
```
[devshell]$ cargo doc
 Documenting nix-std-rust-hello v0.1.0 (/home/waalge/x/sandpit/nix-std-rust-hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
[devshell]$ ls
Cargo.lock  Cargo.toml  flake.lock  flake.nix  nix  rustfmt.toml  src  target
[devshell]$ git add Cargo.lock
[devshell]$ std //hello/packages/default:build
```
Tab completion working correctly. However the `std` command exits with no message, just exit code 1, until I'd left the env and re-entered. 
 
 
 --- 
 
 If you want any testing for idiot proofing the guide :raising_hand:

**Comment by jmgilman** [comment]
Hi,

Sorry about the blog. I recently moved to Cloudflare and I think there was an incompatibility with the way they do SSL. It should be fixed now. I would recommend checking out the [`std` book](https://jmgilman.github.io/std-book/) for an up-to-date guide. It'd be great to get feedback on the experience of using it as it is written as more of a guide than more documentation.

**Comment by waalge** [comment]
Thanks :) I can confirm your blog is now available to me. 
I'll check out the book.

**Comment by blaggacao** [comment]
Thanks a lot for this report! :handshake: 

The above commit series should tackle all points, iiuc.

Please shout if there's still something else due for polishing :smile:
