### ISSUE TITLE
colons in packages/apps names break std cli

### ISSUE THREAD

**Issue by jbgi** [divnix/std#167]
Colons in package names is the default for [haskell.nix generated flake packages](https://input-output-hk.github.io/haskell.nix/tutorials/getting-started-flakes.html#working-with-a-project), hence the issue.
Eg. in https://github.com/input-output-hk/cardano-prelude/pull/176
```
$ std //prelude/apps/cardano-prelude-test:test:prelude-tests:run
error: flake 'git+file:///home/jbgi/Dev/iohk/cardano-prelude' does not provide attribute 'packages.x86_64-linux.__std.actions.x86_64-linux.prelude.apps.cardano-prelude-test.test:prelude-tests:run', 'legacyPackages.x86_64-linux.__std.actions.x86_64-linux.prelude.apps.cardano-prelude-test.test:prelude-tests:run' or '__std.actions.x86_64-linux.prelude.apps.cardano-prelude-test.test:prelude-tests:run'
```
(same for `std //prelude/apps/"cardano-prelude-test:test:prelude-tests":run`)

**Comment by blaggacao** [comment]
Looks like a simple change to the regex fixes this https://regex101.com/r/hsxPiK/1

**Comment by blaggacao** [comment]
Although I'm quite confident of [the solution](https://github.com/divnix/std/pull/172), I'd appreciate a real-world test on that PR...
