### ISSUE TITLE
how to produce cells with arion docker compositions

### ISSUE THREAD

**Issue by dzmitry-lahoda** [divnix/std#173]
is std works well with arion docker composes https://docs.hercules-ci.com/arion/ ?

**Comment by blaggacao** [comment]
I see anproblem with the current integration point https://docs.hercules-ci.com/arion/#_arion_pkgs_nix (& `arion-compose.nix`).

What would be needed is probably a flake interface that we could `std.harvest` onto for smooth compatibility.

https://github.com/divnix/hive 's `make-mead.nix` & `make-honey.nix` can give an idea how such a integration could then look like.

I'd love to see that happening!

**Comment by GTrunSec** [comment]
solved by: https://github.com/divnix/hive/pull/1
