### ISSUE TITLE
Unable to use nix-shell shim with exported devshells

### ISSUE THREAD

**Issue by jmgilman** [divnix/std#186]
Something seems to be inherently breaking the standard `nix-shell` shim. Here is a [minimum reproducible example](https://gist.github.com/jmgilman/340e13c735d43efb99610d1da3f9ef83). Attempting to use the shim:

```
$ nix-shell
 error: expression does not evaluate to a derivation (or a set or list of those)
```

**Comment by blaggacao** [comment]
My best guess would be the compat is not yet trimmed to `devShells.default`

**Comment by blaggacao** [comment]
This solves it:
```nix
builtins.removeAttrs (
  import
  (
    let
      lock = builtins.fromJSON (builtins.readFile ./flake.lock);
    in
      fetchTarball {
        url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
        sha256 = lock.nodes.flake-compat.locked.narHash;
      }
  )
  {src = ./.;}
)
.shellNix ["__functor"]
```

`nix-shell` misinterprets a functor as an obligatory (instead of correctly as a facultative) function.

I think this is an upstream bug in nixpkgs, similar bugs for `nix build` have been resovled.

**Comment by blaggacao** [comment]
upstream fix: https://github.com/edolstra/flake-compat/pull/47

**Comment by jmgilman** [comment]
Yep, that fixes it. Thanks! I'll keep this open until upstream merges.

**Comment by blaggacao** [comment]
Upstream was merged :tada:
