### ISSUE TITLE
?

### ISSUE THREAD

**Issue by nixinator** [divnix/std#20]
![image](https://user-images.githubusercontent.com/66913205/152507532-2403bef8-ec0a-440e-ae86-20f4b60045eb.png)

**Comment by blaggacao** [comment]
I _do_ like cats. :smile:

**Comment by blaggacao** [comment]
I think what you'd been looking for is for an example in the examples section, which is soon to come.

**Comment by blaggacao** [comment]
?

**Comment by blaggacao** [comment]
Next `?`-level unlocked: https://github.com/divnix/std/commit/d406f0a555d01c5d75301cf2933c24e6325b1b5e
