### ISSUE TITLE
Move from numtide/devshell to cachix/devenv

### ISSUE THREAD

**Issue by blaggacao** [divnix/std#210]
https://twitter.com/zimbatm/status/1605232062423760907

Figure out what needs to be done.

**Comment by jmgilman** [comment]
The last time I looked at this, I wasn't impressed. Perhaps it's gotten better.

**Comment by blaggacao** [comment]
It looks like we can't sensible choose to forgo the community momentum attached to `devenv`.

**Comment by blaggacao** [comment]
I played a little with `devenv` today and after that I don't see this feasible for v1.

It's escpecially annoying that `devenv` works with a synthetic flake generation to mimick an interface into flake.

However, that introduces a media break into the nix lingua franca layer (of control).

That's pretty much a no-go if we strive to integrate and _removing_ media breaks, where possible.

**Comment by terlar** [comment]
They also have a flake.nix compatible way:
https://devenv.sh/guides/using-with-flakes/#getting-started

However it doesn’t seem like the devenv command will work then. When running a devenv command it will generate the lock files and all that jazz.

Seems one looses the devenv.yaml support and also some features like this:
https://devenv.sh/composing-using-imports/

**Comment by blaggacao** [comment]
That is a good data point.

On the other hand, when doing this then actually `numtide/devshell` has the better use-case to documentation fit.

If we instead point people to `devenv`, we then have to send them to a reeducation camp first, because they would want to start doing all the things the `devenv`-way.

And that would break more than one promised use case.

This can cause coercive pressure that grows into technical backlog based on a marketing innovation without an actual technically sound reason.

The problem could also be inversed: can we sprint & maintain `devshell` to feature parity (including docs & marketing innovation)?

**Comment by blaggacao** [comment]
This is being out-acoped for the forseeable future, si ce devshell doesn't leave any urgent functional gaps. During a transitionary period, we may need to keep devshell under maintenance.
