### ISSUE TITLE
Add inferface of the common lib for std organelles.

### ISSUE THREAD

**Issue by GTrunSec** [divnix/std#28]
I saw your @blaggacao work on [bitte-cells](https://github.com/input-output-hk/bitte-cells) that was pretty cool and practical such as [_writers](https://github.com/input-output-hk/bitte-cells/tree/main/cells/_writers).  Suddenly, one of the questions appeared in my mind, why not write a common lib for std orancells and especially like `runner` and `writers.`.

**Comment by blaggacao** [comment]
I'm going to close this as a duplicate of #27
