### ISSUE TITLE
Unclear comment in rust project template

### ISSUE THREAD

**Issue by gkobeaga** [divnix/std#290]
It is not clear which field it refers to with "stable".

https://github.com/divnix/std/blob/b8bb69b520007833dea1e4cda8ffd1b39f41eb02/cells/presets/templates/rust/nix/repo/rust.nix#L7-L8

Maybe the comment is outdated.

**Comment by blaggacao** [comment]
Thanks for noting! fixed in https://github.com/divnix/std/commit/65d7e4462187d3aaf76472939e51cdb1748fe0b7
