### ISSUE TITLE
How do you integrate a `README.md` with the TUI?

### ISSUE THREAD

**Issue by joneshf** [divnix/std#293]
If I open the TUI with `std`, the interface lets me inspect a target with`?`. This new view shows three tabs for the cell, block, and target. Each of them has a message indicating that they don't have a readme and instructions on how to create one:
```
🥺 No Readme available ...

💡 But hey! You could create one ...

💪 Start with: `$EDITOR nix/example/Readme.md`

👉 It will also be rendered in the docs!
```

If I make that `nix/example/Readme.md` file, nothing seems to change. It doesn't seem to matter what the case is. Something is missing, but it's not clear what. What other steps need to be done in order to integrate a `README.md`?

**Comment by blaggacao** [comment]
You may need to make sure to add `nix/example/Readme.md` to git version control. Unfortuntately, that is all too often forgotten and `nix` ignores files that are not (yet) under version contol.

Let me know if that was it.

**Comment by joneshf** [comment]
Yep. That was it. Thanks!

Maybe the message could mention something like that as well?

**Comment by blaggacao** [comment]
Good idea, [this](https://github.com/paisano-nix/tui/commit/f0809101b957e831ff5ae3be432397a0da9149b7) will eventually trickle down &mdash; with low priority &mdash; into `std`.

**Comment by joneshf** [comment]
Awesome! Thanks for that!

**Comment by blaggacao** [comment]
Unless I made a mistake, this should have landed in https://github.com/divnix/std/tree/v0.21.1

**Comment by joneshf** [comment]
Yep! That's great. Thanks for the update!
