### ISSUE TITLE
Create library of the writers

### ISSUE THREAD

**Issue by GTrunSec** [divnix/std#32]
Response: https://github.com/divnix/std/issues/27#issuecomment-1039789838

I did the [cliche](https://github.com/GTrunSec/DevSecOps-cells/blob/main/cells/_writers/library.nix) implement here. could you create a new repo for that or somehow? thanks

**Comment by blaggacao** [comment]
This is awesome, thanks!

**Comment by blaggacao** [comment]
This seems increasingly out of scope, as is.

But we may want to brainstorm & groom similar issues that focus alongside the SDLC in the coming iterations.
