### ISSUE TITLE
A way to reduce repetitive eval jobs

### ISSUE THREAD

**Issue by GTrunSec** [divnix/std#68]
Through the relationship between organelles and the files structure, that we can accurately evaluate the changed organelle by watching this organelle folder status. Then update it in the init cache to speed up the evaluation.

- Yeh, We only update or eval  the modified organelle to the `std.init` cache instead of eval `std.init` repeatedly.
- Hook the watcher when std-gui running.

![image](https://user-images.githubusercontent.com/21156405/169687537-05942e94-eea5-42e0-a21b-cf617b640be7.png)

**Comment by blaggacao** [comment]
That's pretty much what `numtide/nix-eval-cache` does. It's just not yet in the right shape to be implemented.

**Comment by blaggacao** [comment]
> would it help us to eval things in parallel with nix-eval-jobs?

Ideally, evaluating the metadata should be cheap, but for some reason it isn't.

I haven't yet been able to figure out where a dependency on expensive evals is introduced and why.

But metadata was intended to only scrape attributes that don't require an eval of the target.

I may need some debugging help on this one. It's a bit contrived.

**Comment by blaggacao** [comment]
https://github.com/divnix/std/commit/bf37951dbcab29794c3990d495e1312a9663d3d5 takes this pretty much as far as it can currently get, short of implementing proper eval caching on the Nix side. But I think, this is good enough for the time being.
