### ISSUE TITLE
Publish Action for oci-images / normal packages

### ISSUE THREAD

**Issue by blaggacao** [divnix/std#94]
```
path=$(nix eval --raw .#x86_64-linux.cloud.oci-images.jormungandr-fund9-dryrun --impure)
  hash=${path:11:[3](https://github.com/input-output-hk/cardano-gov-world/runs/7335000765?check_suite_focus=true#step:4:3)2}
  url="https://iog.cachix.org/$hash.narinfo";
  if curl --output /dev/null --silent --head --fail "$url"; then
    echo "Nothing to push!!!"
  else
    nix run .#x86_6[4](https://github.com/input-output-hk/cardano-gov-world/runs/7335000765?check_suite_focus=true#step:4:4)-linux.cloud.oci-images.jormungandr-fund[9](https://github.com/input-output-hk/cardano-gov-world/runs/7335000765?check_suite_focus=true#step:4:9)-dryrun.copyToRegistry --show-trace --impure
  fi
```

@garbas @nrdxp

**Comment by nrdxp** [comment]
related to NixOS/nix#3946

We can add this as a compatibility layer for now, especially since nix-build-uncached relies on legacy commands, meaning we lose the flake `nixConfig`, so I think you're approach is more minimal and appropriate for a flake based system like `std` for sure.

**Comment by blaggacao** [comment]
https://github.com/input-output-hk/mamba-world/commit/35c2d037e2482446754b1af06cdbe657e05b70a2

**Comment by blaggacao** [comment]
This is implemented, but without the already-exists-query. To that end, we're discussing https://github.com/divnix/std-action#2
